[profile]
name = "base"

packages = [
  "app-admin/sudo",
  "sys-kernel/linux-firmware",
]

package_license = [
  "sys-kernel/linux-firmware *",
]

system_services = [
  "systemd-resolved.service",
  "sshd.service",
]
