[profile]
name = "sway"
portage_profile = "default/linux/arm64/23.0/desktop/systemd"

packages = [
  "app-arch/p7zip",
  "app-arch/unzip",
  "app-arch/zip",
  "app-editors/mousepad",
  "app-editors/nano",
  "app-editors/neovim",
  "app-misc/fastfetch",
  "app-misc/jq",
  "app-misc/tmux",
  "app-misc/yq",
  "app-portage/eix",
  "app-portage/gentoolkit",
  "app-shells/fzf",
  "app-shells/zsh",
  "app-text/evince",
  "gnome-base/gvfs",
  "gnome-extra/nm-applet",
  "gnome-extra/polkit-gnome",
  "gui-apps/foot",
  "gui-apps/gtkgreet",
  "gui-apps/grim",
  "gui-apps/mako",
  "gui-apps/slurp",
  "gui-apps/swappy",
  "gui-apps/swaybg",
  "gui-apps/swayidle",
  "gui-apps/swaylock",
  "gui-apps/waybar",
  "gui-apps/wl-clipboard",
  "gui-apps/wlogout",
  "gui-apps/wofi",
  "gui-libs/greetd",
  "gui-libs/xdg-desktop-portal-wlr",
  "gui-wm/sway",
  "media-fonts/fontawesome",
  "media-fonts/noto",
  "media-fonts/noto-cjk",
  "media-fonts/noto-emoji",
  "media-gfx/imv",
  "media-libs/vulkan-loader",
  "media-sound/alsa-utils",
  "media-sound/pavucontrol",
  "media-sound/playerctl",
  "media-video/mpv",
  "media-video/pipewire",
  "media-video/wireplumber",
  "net-misc/chrony",
  "net-misc/curl",
  "net-misc/networkmanager",
  "net-misc/rsync",
  "net-misc/wget",
  "net-wireless/blueman",
  "net-wireless/bluez",
  "sys-apps/dbus",
  "sys-apps/ethtool",
  "sys-apps/fd",
  "sys-apps/lm-sensors",
  "sys-apps/pciutils",
  "sys-apps/ripgrep",
  "sys-apps/smartmontools",
  "sys-apps/usbutils",
  "sys-apps/xdg-desktop-portal",
  "sys-apps/xdg-desktop-portal-gtk",
  "sys-auth/polkit",
  "sys-auth/rtkit",
  "sys-fs/exfatprogs",
  "sys-fs/ntfs3g",
  "sys-power/acpilight",
  "sys-power/upower",
  "sys-process/btop",
  "www-client/firefox-bin",
  "x11-base/xwayland",
  "x11-misc/shared-mime-info",
  "x11-misc/xdg-user-dirs",
  "x11-misc/xdg-utils",
  "x11-themes/adwaita-icon-theme",
  "x11-themes/papirus-icon-theme",
  "xfce-base/thunar",
]

rebuild = [
  "sys-auth/pambase",
]

groups = [
  "audio",
  "input",
  "pipewire",
  "plugdev",
  "video",
]

make_conf = [
  { key = "VIDEO_CARDS", value = "vc4 v3d" },
]

package_use = [
  "dev-libs/libdbusmenu gtk3",
  "gnome-extra/nm-applet appindicator",
  "gui-apps/gtkgreet layershell",
  "gui-apps/swaybg gdk-pixbuf",
  "gui-apps/waybar backlight evdev mpris network tray upower",
  "gui-apps/wlogout bash-completion zsh-completion -fish-completion -man",
  "gui-wm/sway wallpapers swaybar swaynag -tray",
  "media-video/pipewire bluetooth pipewire-alsa pulseaudio sound-server ssl systemd v4l -system-service",
  "media-video/wireplumber systemd -system-service",
  "net-misc/networkmanager systemd tools -dhclient -dhcpcd -resolvconf",
  "net-wireless/blueman network",
  "net-wireless/bluez mesh obex readline",
  "sys-auth/seatd systemd -server",
  "xfce-base/thunar -trash-panel-plugin",
]

bootstrap = [
  { packages = ["dev-python/docutils"], use = ["-truetype"], rebuild = ["dev-python/pillow"] },
]

accept_keywords = [
  "app-editors/neovim ~arm64",
  "app-misc/fastfetch ~arm64",
  "dev-libs/date ~arm64",
  "gui-apps/gtkgreet ~arm64",
  "gui-apps/mako ~arm64",
  "gui-apps/waybar ~arm64",
  "gui-apps/swappy **",
  "gui-apps/wlogout ~arm64",
  "gui-apps/wofi **",
  "gui-libs/greetd ~arm64",
  "gui-libs/xdg-desktop-portal-wlr ~arm64",
  "media-sound/pavucontrol ~arm64",
  "sys-fs/exfatprogs ~arm64",
  "sys-power/acpilight **",
]

system_services = [
  "NetworkManager.service",
  "bluetooth.service",
  "chronyd.service",
  "greetd.service",
]

user_services = [
  "pipewire.socket",
  "pipewire-pulse.socket",
  "wireplumber.service",
  "swayidle.service",
  "mako.service",
  "waybar.service",
  "polkit-gnome-authentication-agent-1.service",
  "nm-applet.service",
  "blueman-applet.service",
  "xdg-user-dirs-update.service",
]

files = [
  { source = "sway/etc/environment.d/10-sway-session.conf", target = "/etc/environment.d/10-sway-session.conf", mode = "0644" },
  { source = "sway/etc/greetd/config.toml", target = "/etc/greetd/config.toml", mode = "0644" },
  { source = "sway/etc/greetd/environments", target = "/etc/greetd/environments", mode = "0644" },
  { source = "sway/etc/greetd/gtkgreet.css", target = "/etc/greetd/gtkgreet.css", mode = "0644" },
  { source = "sway/etc/greetd/sway-config", target = "/etc/greetd/sway-config", mode = "0644" },
  { source = "sway/etc/polkit-1/rules.d/50-uconsole-power.rules", target = "/etc/polkit-1/rules.d/50-uconsole-power.rules", mode = "0644" },
  { source = "sway/etc/sway/config", target = "/etc/sway/config", mode = "0644" },
  { source = "sway/etc/systemd/logind.conf.d/10-power-key.conf", target = "/etc/systemd/logind.conf.d/10-power-key.conf", mode = "0644" },
  { source = "sway/etc/systemd/user/blueman-applet.service", target = "/etc/systemd/user/blueman-applet.service", mode = "0644" },
  { source = "sway/etc/systemd/user/mako.service", target = "/etc/systemd/user/mako.service", mode = "0644" },
  { source = "sway/etc/systemd/user/nm-applet.service", target = "/etc/systemd/user/nm-applet.service", mode = "0644" },
  { source = "sway/etc/systemd/user/polkit-gnome-authentication-agent-1.service", target = "/etc/systemd/user/polkit-gnome-authentication-agent-1.service", mode = "0644" },
  { source = "sway/etc/systemd/user/sway-session.target", target = "/etc/systemd/user/sway-session.target", mode = "0644" },
  { source = "sway/etc/systemd/user/swayidle.service", target = "/etc/systemd/user/swayidle.service", mode = "0644" },
  { source = "sway/etc/systemd/user/waybar.service", target = "/etc/systemd/user/waybar.service", mode = "0644" },
  { source = "sway/etc/systemd/user/wlogout.service", target = "/etc/systemd/user/wlogout.service", mode = "0644" },
  { source = "sway/etc/systemd/user/wofi-drun.service", target = "/etc/systemd/user/wofi-drun.service", mode = "0644" },
  { source = "sway/etc/systemd/user/xdg-user-dirs-update.service", target = "/etc/systemd/user/xdg-user-dirs-update.service", mode = "0644" },
  { source = "sway/etc/wlogout/layout", target = "/etc/wlogout/layout", mode = "0644" },
  { source = "sway/etc/wlogout/style.css", target = "/etc/wlogout/style.css", mode = "0644" },
  { source = "sway/etc/xdg/foot/foot.ini", target = "/etc/xdg/foot/foot.ini", mode = "0644" },
  { source = "sway/etc/xdg/gtk-3.0/settings.ini", target = "/etc/xdg/gtk-3.0/settings.ini", mode = "0644" },
  { source = "sway/etc/xdg/gtk-4.0/settings.ini", target = "/etc/xdg/gtk-4.0/settings.ini", mode = "0644" },
  { source = "sway/etc/xdg/mako/config", target = "/etc/xdg/mako/config", mode = "0644" },
  { source = "sway/etc/xdg/waybar/config", target = "/etc/xdg/waybar/config", mode = "0644" },
  { source = "sway/etc/xdg/waybar/style.css", target = "/etc/xdg/waybar/style.css", mode = "0644" },
  { source = "sway/etc/xdg/xdg-desktop-portal/sway-portals.conf", target = "/etc/xdg/xdg-desktop-portal/sway-portals.conf", mode = "0644" },
  { source = "sway/usr/local/bin/uconsole-swayidle", target = "/usr/local/bin/uconsole-swayidle", mode = "0755" },
]
