[board]
name = "uconsole-cm4"
family = "raspberrypi"
arch = "arm64"

[paths]
build_dir = "build"
sources_dir = "build/sources"
cache_dir = "build/cache"
work_dir = "build/work"
artifacts_dir = "build/artifacts"
logs_dir = "build/logs"

[kernel]
version = "6.18.y"
repo = "https://github.com/raspberrypi/linux.git"
ref = "rpi-6.18.y"
source_dir = "build/sources/kernel/linux"
work_dir = "build/work/kernel/6.18.y/linux"
check_dir = "build/work/kernel/6.18.y/apply-check"
patches_dir = "kernel/6.18.y/patches"
defconfig = "bcm2711_defconfig"
arch = "arm64"
cross_compile = "aarch64-linux-gnu-"
image_path = "arch/arm64/boot/Image"
kernel_image_name = "kernel8.img"
dtb_glob = "arch/arm64/boot/dts/broadcom/*.dtb"
dtbo_glob = "arch/arm64/boot/dts/overlays/*.dtbo"
overlays_readme = "arch/arm64/boot/dts/overlays/README"

[firmware]
repo = "https://github.com/raspberrypi/firmware.git"
ref = "dd28ccd67f16e60f5739dc779060be218b28eb1e"
source_dir = "build/sources/firmware/raspberrypi"
work_dir = "build/work/firmware/uconsole-cm4"
boot_files = [
  "boot/LICENCE.broadcom",
  "boot/bootcode.bin",
  "boot/fixup4.dat",
  "boot/fixup4cd.dat",
  "boot/fixup4db.dat",
  "boot/fixup4x.dat",
  "boot/start4.elf",
  "boot/start4cd.elf",
  "boot/start4db.elf",
  "boot/start4x.elf",
]
config_txt = [
  "arm_64bit=1",
  "kernel=kernel8.img",
  "disable_overscan=1",
  "dtparam=audio=on",
  "[pi4]",
  "max_framebuffers=2",
  "[all]",
  "ignore_lcd=1",
  "dtoverlay=dwc2,dr_mode=host",
  "dtoverlay=vc4-kms-v3d-pi4,cma-384",
  "dtoverlay=clockworkpi-uconsole",
  "dtoverlay=audremap,pins_12_13",
  "dtparam=spi=on",
  "gpio=10=ip,np",
  "dtparam=ant2",
]
cmdline = [
  "rootfstype=ext4",
  "rootwait",
  "fsck.repair=yes",
  "console=serial0,115200",
  "console=tty1",
]

[rootfs]
stage3 = "build/sources/rootfs/stage3-arm64-systemd-20260614T234629Z.tar.xz"
stage3_url = "https://distfiles.gentoo.org/releases/arm64/autobuilds/20260614T234629Z/stage3-arm64-systemd-20260614T234629Z.tar.xz"
stage3_sha512 = "4ca46833f03fc703e6a59c5ddd052916628322c46ae9623ccbd4997b983cc419ec5fc2aea10faa8f10cbde225fc35b5b5a87ff04619a5bca0f67c29611905baa"
stage3_size = 430976500
repository_url = "https://github.com/gentoo/gentoo.git"
repository_ref = "master"
repository_dir = "build/sources/rootfs/gentoo"
portage_repositories_dir = "rootfs/portage"
jobs = 4
emerge_jobs = 10
emerge_load_average = 10
overlay_dir = "rootfs/overlay"
work_dir = "build/work/rootfs/uconsole-cm4"
hostname = "uconsole"
timezone = "UTC"
locale = "en_US.UTF-8"
keymap = "us"

[rootfs.desktop]
profile = "sway"

[rootfs.user]
groups = ["wheel", "audio", "video", "input", "users"]

[disk]
partition_table = "gpt"
boot_label = "UCONSOLE"
root_label = "gentoo-root"

[image]
name = "gentoo-uconsole-cm4.img"
size_mib = 16384
boot_size_mib = 512
work_dir = "build/work/image/uconsole-cm4"
compress = true
